package group.jsjxh.community.bean;

public class QuesTagKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUES_TAG.QESNO
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    private Integer qesno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUES_TAG.TAGNO
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    private Integer tagno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUES_TAG.QESNO
     *
     * @return the value of TB_QUES_TAG.QESNO
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    public Integer getQesno() {
        return qesno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUES_TAG.QESNO
     *
     * @param qesno the value for TB_QUES_TAG.QESNO
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    public void setQesno(Integer qesno) {
        this.qesno = qesno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUES_TAG.TAGNO
     *
     * @return the value of TB_QUES_TAG.TAGNO
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    public Integer getTagno() {
        return tagno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUES_TAG.TAGNO
     *
     * @param tagno the value for TB_QUES_TAG.TAGNO
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    public void setTagno(Integer tagno) {
        this.tagno = tagno;
    }
}