package group.jsjxh.community.bean;

import java.util.Date;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUES.QNO
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private Integer qno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUES.QTITLE
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private String qtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUES.QCREATE_AT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private Date qcreateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUES.QAUTHOR
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private Integer qauthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUES.QUPDATE_AT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private Date qupdateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUES.QREAD
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private Integer qread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUES.QLIKE
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private Integer qlike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUES.QSHIT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private Integer qshit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUES.QCONTENT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private String qcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUES.QNO
     *
     * @return the value of TB_QUES.QNO
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public Integer getQno() {
        return qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUES.QNO
     *
     * @param qno the value for TB_QUES.QNO
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setQno(Integer qno) {
        this.qno = qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUES.QTITLE
     *
     * @return the value of TB_QUES.QTITLE
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public String getQtitle() {
        return qtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUES.QTITLE
     *
     * @param qtitle the value for TB_QUES.QTITLE
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setQtitle(String qtitle) {
        this.qtitle = qtitle == null ? null : qtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUES.QCREATE_AT
     *
     * @return the value of TB_QUES.QCREATE_AT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public Date getQcreateAt() {
        return qcreateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUES.QCREATE_AT
     *
     * @param qcreateAt the value for TB_QUES.QCREATE_AT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setQcreateAt(Date qcreateAt) {
        this.qcreateAt = qcreateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUES.QAUTHOR
     *
     * @return the value of TB_QUES.QAUTHOR
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public Integer getQauthor() {
        return qauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUES.QAUTHOR
     *
     * @param qauthor the value for TB_QUES.QAUTHOR
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setQauthor(Integer qauthor) {
        this.qauthor = qauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUES.QUPDATE_AT
     *
     * @return the value of TB_QUES.QUPDATE_AT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public Date getQupdateAt() {
        return qupdateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUES.QUPDATE_AT
     *
     * @param qupdateAt the value for TB_QUES.QUPDATE_AT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setQupdateAt(Date qupdateAt) {
        this.qupdateAt = qupdateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUES.QREAD
     *
     * @return the value of TB_QUES.QREAD
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public Integer getQread() {
        return qread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUES.QREAD
     *
     * @param qread the value for TB_QUES.QREAD
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setQread(Integer qread) {
        this.qread = qread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUES.QLIKE
     *
     * @return the value of TB_QUES.QLIKE
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public Integer getQlike() {
        return qlike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUES.QLIKE
     *
     * @param qlike the value for TB_QUES.QLIKE
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setQlike(Integer qlike) {
        this.qlike = qlike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUES.QSHIT
     *
     * @return the value of TB_QUES.QSHIT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public Integer getQshit() {
        return qshit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUES.QSHIT
     *
     * @param qshit the value for TB_QUES.QSHIT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setQshit(Integer qshit) {
        this.qshit = qshit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUES.QCONTENT
     *
     * @return the value of TB_QUES.QCONTENT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public String getQcontent() {
        return qcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUES.QCONTENT
     *
     * @param qcontent the value for TB_QUES.QCONTENT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setQcontent(String qcontent) {
        this.qcontent = qcontent == null ? null : qcontent.trim();
    }
}