package group.jsjxh.community.bean;

import java.util.Date;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAG.TNO
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private Integer tno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAG.TNAME
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAG.TCREATE_AT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    private Date tcreateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAG.TNO
     *
     * @return the value of TB_TAG.TNO
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAG.TNO
     *
     * @param tno the value for TB_TAG.TNO
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAG.TNAME
     *
     * @return the value of TB_TAG.TNAME
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAG.TNAME
     *
     * @param tname the value for TB_TAG.TNAME
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAG.TCREATE_AT
     *
     * @return the value of TB_TAG.TCREATE_AT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public Date getTcreateAt() {
        return tcreateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAG.TCREATE_AT
     *
     * @param tcreateAt the value for TB_TAG.TCREATE_AT
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    public void setTcreateAt(Date tcreateAt) {
        this.tcreateAt = tcreateAt;
    }
}