package group.jsjxh.community.bean;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.ID
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.ACCOUNT_ID
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.NAME
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.TOKEN
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.CREATE_AT
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.UPDATE_AT
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.PICURL
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    private String picurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.ID
     *
     * @return the value of TB_USER.ID
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.ID
     *
     * @param id the value for TB_USER.ID
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.ACCOUNT_ID
     *
     * @return the value of TB_USER.ACCOUNT_ID
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.ACCOUNT_ID
     *
     * @param accountId the value for TB_USER.ACCOUNT_ID
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.NAME
     *
     * @return the value of TB_USER.NAME
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.NAME
     *
     * @param name the value for TB_USER.NAME
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.TOKEN
     *
     * @return the value of TB_USER.TOKEN
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.TOKEN
     *
     * @param token the value for TB_USER.TOKEN
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.CREATE_AT
     *
     * @return the value of TB_USER.CREATE_AT
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.CREATE_AT
     *
     * @param createAt the value for TB_USER.CREATE_AT
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.UPDATE_AT
     *
     * @return the value of TB_USER.UPDATE_AT
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.UPDATE_AT
     *
     * @param updateAt the value for TB_USER.UPDATE_AT
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.PICURL
     *
     * @return the value of TB_USER.PICURL
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.PICURL
     *
     * @param picurl the value for TB_USER.PICURL
     *
     * @mbg.generated Sat Nov 23 11:24:40 CST 2019
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }
}