spring:
  datasource:
    url: jdbc:h2:D:/h2database/community
    username: h2
    password: 123456
    driver-class-name: org.h2.Driver
  jackson:
    date-format: yyyy/MM/dd hh:mm:ss
  thymeleaf:
    cache: false
server:
  port: 8887
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.xml