spring:
  datasource:
    url: jdbc:h2:D:/h2database/community
    username: h2
    password: 123456
    driver-class-name: org.h2.Driver
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  profiles: test
server:
  port: 8887
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.xml
  type-aliases-package: java.lang;java.util;group.jsjxh.community.bean;