spring:
  datasource:
    url: jdbc:h2:~/community
    username: h2
    password: 123456
    driver-class-name:
  jackson:
    date-format: yyyy/MM/dd hh:mm:ss
server:
  port: 8887
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.xml