spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy/MM/dd hh:mm:ss
server:
  port: 8887
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.xml