package group.jsjxh.community.dao;

import group.jsjxh.community.bean.QuesTagExample;
import group.jsjxh.community.bean.QuesTagKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuesTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_QUES_TAG
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    long countByExample(QuesTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_QUES_TAG
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    int deleteByExample(QuesTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_QUES_TAG
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    int deleteByPrimaryKey(QuesTagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_QUES_TAG
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    int insert(QuesTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_QUES_TAG
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    int insertSelective(QuesTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_QUES_TAG
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    List<QuesTagKey> selectByExample(QuesTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_QUES_TAG
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") QuesTagKey record, @Param("example") QuesTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_QUES_TAG
     *
     * @mbg.generated Sat Nov 23 13:06:57 CST 2019
     */
    int updateByExample(@Param("record") QuesTagKey record, @Param("example") QuesTagExample example);
}