package group.jsjxh.community.dao;

import group.jsjxh.community.bean.Question;
import group.jsjxh.community.bean.Tag;
import group.jsjxh.community.bean.TagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagMapper {

    List<Tag> selectTagByQuestionNo(Integer questionNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAG
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    long countByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAG
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    int deleteByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAG
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    int deleteByPrimaryKey(Integer tno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAG
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAG
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    int insertSelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAG
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    List<Tag> selectByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAG
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    Tag selectByPrimaryKey(Integer tno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAG
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tag record, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAG
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    int updateByExample(@Param("record") Tag record, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAG
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    int updateByPrimaryKeySelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAG
     *
     * @mbg.generated Sat Nov 23 12:36:46 CST 2019
     */
    int updateByPrimaryKey(Tag record);
}